name: easy_assistance_app
description: "A new Flutter project."
publish_to: 'none'

# Application version
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.17.5
  shared_preferences: ^2.0.18
  provider: ^6.1.2 # Added a valid version for provider
  http: ^1.2.2
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/images/logo.png
    - lib/images/registerPage.png
    - lib/images/google.jpeg
    - lib/images/avatar1.png
    - lib/images/avatar2.png
    - lib/images/avatar3.png
    - lib/images/avatar4.png
    - lib/images/avatar5.png
    - lib/images/avatar6.png
    - lib/images/avatar7.png
    - lib/images/avatar8.png
    - lib/Images/1stImage.jpg
    - lib/Images/2ndImage.jpg
    - lib/Images/3rdImage.jpg
    - lib/Images/4thImage.jpg
