name: easy_assistance_app
description: "A new Flutter project."
publish_to: 'none'

# Application version
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0" # Adjusted for compatibility with Dart 3.x

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0 # Updated to a stable and compatible version
  cloud_firestore: ^4.17.5
  shared_preferences: ^2.0.18
  provider: ^6.1.2 # Added a compatible version
  http: ^1.2.2
  intl: ^0.18.0 # Added intl for internationalization
  flutterfire_cli: ^1.0.1-dev.4
  google_sign_in: 5.4.2
  email_otp: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/images/logo.png
    - lib/images/registerPage.png
    - lib/images/google.jpeg
    - lib/images/avatar1.png
    - lib/images/avatar2.png
    - lib/images/avatar3.png
    - lib/images/avatar4.png
    - lib/images/avatar5.png
    - lib/images/avatar6.png
    - lib/images/avatar7.png
    - lib/images/avatar8.png
