// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import    'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC5tlKrbwpfm3myPIKvpTmr8FzrkAaWF4',
    appId: '1:67562738460:web:ccc936dc2f0dfcee1920d9',
    messagingSenderId: '67562738460',
    projectId: 'ea-regis',
    authDomain: 'ea-regis.firebaseapp.com',
    storageBucket: 'ea-regis.firebasestorage.app',
    measurementId: 'G-VRL3FQQ66J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXePq00Ia1QlmRxVW6aC7_cOS2VdmjzQ8',
    appId: '1:67562738460:android:0d8bdded9a90223f1920d9',
    messagingSenderId: '67562738460',
    projectId: 'ea-regis',
    storageBucket: 'ea-regis.firebasestorage.app',
  );
}
