// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfMwecmJCQl3-a2YM2NwGDxbm6w79gGsA',
    appId: '1:699807150469:web:e17ec7d6de22334d2ad4ec',
    messagingSenderId: '699807150469',
    projectId: 'easyassistanceapplication',
    authDomain: 'easyassistanceapplication.firebaseapp.com',
    storageBucket: 'easyassistanceapplication.firebasestorage.app',
    measurementId: 'G-92JKQCYJMN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8snCpjH9Wds1CBoTgHwF2hXq_hsGtxHk',
    appId: '1:699807150469:android:e0c572403763abbb2ad4ec',
    messagingSenderId: '699807150469',
    projectId: 'easyassistanceapplication',
    storageBucket: 'easyassistanceapplication.firebasestorage.app',
  );

}